# Generated by Django 5.0.2 on 2024-03-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('LinkedIn', models.CharField(max_length=100)),
                ('Instagram', models.CharField(max_length=100)),
                ('Behance', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='ProjectImage',
        ),
    ]
