# Generated by Django 5.0.2 on 2024-03-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_aboutimage_profile_rename_image_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='imageName',
            new_name='image_name',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_blob',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
